# Generated by Django 5.0.4 on 2024-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_dadosmedico_valor_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='valor_consulta',
            field=models.CharField(max_length=100),
        ),
    ]
